
package rental;

import db.Koneksi;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import model.Sewa;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;




public class Penyewa extends javax.swing.JFrame {

    Sewa sewa;
    public Penyewa() {
        initComponents();
        setLocationRelativeTo(null);
        resetTable("");
    }
    
    public ArrayList<Sewa> getSewaList(String keyword){
     ArrayList<Sewa> sewaList = new ArrayList<Sewa>();
     Koneksi koneksi =  new Koneksi();
     Connection connection = koneksi.getConnection();
     
     String query ="SELECT * FROM penyewa"+keyword;
     Statement st;
     ResultSet rs;
     
     try{
         st = connection.createStatement();
         rs = st.executeQuery(query);
         while (rs.next()){
             sewa = new Sewa(
                     rs.getInt("no"),
                     rs.getString("nama"),
                     rs.getString("alamat"),
                     rs.getString("no_telepon"),
                     rs.getString("tanggal"));
             sewaList.add(sewa);
         }
     } catch (SQLException | NullPointerException ex){
         System.err.println("Koneksi Null Gagal");
     }
        return sewaList;
    }
    
    public void selectSewa(String keyword){
        ArrayList<Sewa> list = getSewaList(keyword);
        DefaultTableModel model = (DefaultTableModel)tabelpenyewa.getModel();
        Object[] row = new Object[5];
        
        for (int i = 0; i <list.size(); i++){
            row[0] = list.get(i).getNo();
            row[1] = list.get(i).getNama();
            row[2] = list.get(i).getAlamat();
            row[3] = list.get(i).getNo_telepon();
            row[4] = list.get(i).getTanggal();
            
            model.addRow(row);
        }
    }
    
    public final void resetTable(String keyword){
        DefaultTableModel model = (DefaultTableModel)tabelpenyewa.getModel();
        model.setRowCount(0);
        selectSewa(keyword);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JSimpan = new javax.swing.JButton();
        JEdit = new javax.swing.JButton();
        JHapus = new javax.swing.JButton();
        JBatal = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_no = new javax.swing.JTextField();
        txt_nama = new javax.swing.JTextField();
        txt_alamat = new javax.swing.JTextField();
        txt_telepon = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        JSimpan1 = new javax.swing.JButton();
        JEdit1 = new javax.swing.JButton();
        JHapus1 = new javax.swing.JButton();
        JBatal1 = new javax.swing.JButton();
        tgl = new com.toedter.calendar.JDateChooser();
        BNext = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelpenyewa = new javax.swing.JTable();
        BCetak = new javax.swing.JButton();

        JSimpan.setText("SIMPAN");

        JEdit.setText("EDIT");
        JEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JEditActionPerformed(evt);
            }
        });

        JHapus.setText("HAPUS");

        JBatal.setText("BATAL");
        JBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBatalActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(124, 165, 83));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Masukkan Identitas Penyewa", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("No.Transaksi");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Nama");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Alamat");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("No.Tlp");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Tanggal Transaksi");

        JSimpan1.setText("SIMPAN");
        JSimpan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JSimpan1ActionPerformed(evt);
            }
        });

        JEdit1.setText("EDIT");
        JEdit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JEdit1ActionPerformed(evt);
            }
        });

        JHapus1.setText("HAPUS");
        JHapus1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JHapus1ActionPerformed(evt);
            }
        });

        JBatal1.setText("BATAL");
        JBatal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBatal1ActionPerformed(evt);
            }
        });

        BNext.setText("NEXT");
        BNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BNextActionPerformed(evt);
            }
        });

        tabelpenyewa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Nama", "Alamat", "No.Telepon", "Tanggal"
            }
        ));
        tabelpenyewa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelpenyewaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelpenyewa);

        BCetak.setText("CETAK");
        BCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCetakActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(JSimpan1)
                .addGap(54, 54, 54)
                .addComponent(JEdit1)
                .addGap(60, 60, 60)
                .addComponent(JHapus1)
                .addGap(56, 56, 56)
                .addComponent(JBatal1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(txt_no, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 194, Short.MAX_VALUE)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tgl, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(BCetak)
                                .addGap(58, 58, 58)
                                .addComponent(BNext))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_telepon, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_alamat, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(24, 24, 24)
                        .addComponent(jLabel3)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(txt_no, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tgl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))))
                        .addGap(18, 18, 18)
                        .addComponent(txt_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txt_alamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txt_telepon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JSimpan1)
                    .addComponent(JEdit1)
                    .addComponent(JHapus1)
                    .addComponent(JBatal1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BNext)
                    .addComponent(BCetak))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JEditActionPerformed

    }//GEN-LAST:event_JEditActionPerformed

    private void JBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBatalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBatalActionPerformed

    private void JEdit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JEdit1ActionPerformed
        String no = txt_no.getText().toString().trim();
        String nama = txt_nama.getText().toString().trim();
        String alamat = txt_alamat.getText().toString().trim();
        String no_telepon = txt_telepon.getText().toString().trim();
        String tampil ="yyyy-MM-dd";
        SimpleDateFormat fm = new SimpleDateFormat(tampil);
        String tanggal = String.valueOf(fm.format(tgl.getDate()));
        try{
            Koneksi koneksi =  new Koneksi();
            Connection c = koneksi.getConnection();
            String sql = "UPDATE penyewa SET "+"nama=?,alamat=?,no_telepon=?,tanggal=? WHERE no=?";
            PreparedStatement p = c.prepareStatement(sql);
            p.setString(1, nama);
            p.setString(2, alamat);
            p.setString(3, no_telepon);
            p.setString(4,  tanggal);
            p.setString(5, no);
            p.executeUpdate();
            p.close();
            JOptionPane.showMessageDialog(null, "Data Behasil Di Edit");
            resetTable("");
        }catch (SQLException e){
            System.err.println(e);
        }
    }//GEN-LAST:event_JEdit1ActionPerformed

    private void JBatal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBatal1ActionPerformed
        this.hide();
        Main Batal = new Main();
        Batal.show();
    }//GEN-LAST:event_JBatal1ActionPerformed

    private void BNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BNextActionPerformed
        this.hide();
        Mobil Next = new Mobil();
        Next.show();
    }//GEN-LAST:event_BNextActionPerformed

    private void JHapus1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JHapus1ActionPerformed
        // TODO add your handling code here:
        int i = tabelpenyewa.getSelectedRow();
            int pilihan = JOptionPane.showConfirmDialog(
                    null,
                    "Data Di Hapus ?",
                    "Konfirmasi Hapus",
                    JOptionPane.YES_NO_OPTION);
            if(pilihan==0){
                if(i>=0){
                    try{
                        TableModel mode = tabelpenyewa.getModel();
                        Koneksi koneksi = new Koneksi();
                        Connection con  = koneksi.getConnection();
                        String executeQuery = "delete from penyewa where no=?";
                        PreparedStatement ps = con.prepareStatement(executeQuery);
                        ps.setString(1, mode.getValueAt(i,0).toString());
                        ps.executeUpdate();
                    }catch(SQLException ex){
                        System.err.println(ex);
                    }
                }else{
                    JOptionPane.showMessageDialog(null, "Pilih data yang ingin dihapus"); 
                }
            }
            resetTable("");
    }//GEN-LAST:event_JHapus1ActionPerformed

    private void JSimpan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JSimpan1ActionPerformed
        // TODO add your handling code here:
        String no = txt_no.getText().toString().trim();
        String nama = txt_nama.getText().toString().trim();
        String alamat = txt_alamat.getText().toString().trim();
        String no_telepon = txt_telepon.getText().toString().trim();
        String tampil ="yyyy-MM-dd";
        SimpleDateFormat fm = new SimpleDateFormat(tampil);
        String tanggal = String.valueOf(fm.format(tgl.getDate()));
        try{
            Koneksi koneksi =  new Koneksi();
            Connection c = koneksi.getConnection();
            String sql = "INSERT INTO penyewa VALUES (?,?,?,?,?)";
            PreparedStatement p = c.prepareStatement(sql);
            p.setString(1, no);
            p.setString(2, nama);
            p.setString(3, alamat);
            p.setString(4, no_telepon);
            p.setString(5, tanggal);
            p.executeUpdate();
            p.close();
            JOptionPane.showMessageDialog(null, "Data Behasil Di Simpan");
            resetTable("");
        }catch (SQLException e){
            System.err.println(e);
        }

    }//GEN-LAST:event_JSimpan1ActionPerformed

    private void tabelpenyewaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelpenyewaMouseClicked
        // TODO add your handling code here:
        int tabelSewa = tabelpenyewa.getSelectedRow();
        txt_no.setText(tabelpenyewa.getValueAt(tabelSewa, 0).toString());
        txt_nama.setText(tabelpenyewa.getValueAt(tabelSewa, 1).toString());
        txt_alamat.setText(tabelpenyewa.getValueAt(tabelSewa, 2).toString());
        txt_telepon.setText(tabelpenyewa.getValueAt(tabelSewa, 3).toString());
    }//GEN-LAST:event_tabelpenyewaMouseClicked

    private void BCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCetakActionPerformed
        // TODO add your handling code here:
        try{
            Koneksi koneksi =  new Koneksi();
            Connection cn = koneksi.getConnection();
            JasperPrint jp = JasperFillManager.fillReport(getClass().getResourceAsStream("../laporan/LaporanPenyewa.jasper"), null, cn);
            JasperViewer.viewReport(jp, false);
        } catch(Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_BCetakActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Penyewa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Penyewa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Penyewa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Penyewa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Penyewa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BCetak;
    private javax.swing.JButton BNext;
    private javax.swing.JButton JBatal;
    private javax.swing.JButton JBatal1;
    private javax.swing.JButton JEdit;
    private javax.swing.JButton JEdit1;
    private javax.swing.JButton JHapus;
    private javax.swing.JButton JHapus1;
    private javax.swing.JButton JSimpan;
    private javax.swing.JButton JSimpan1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabelpenyewa;
    private com.toedter.calendar.JDateChooser tgl;
    private javax.swing.JTextField txt_alamat;
    private javax.swing.JTextField txt_nama;
    private javax.swing.JTextField txt_no;
    private javax.swing.JTextField txt_telepon;
    // End of variables declaration//GEN-END:variables
}
